export const SPOTS = [
  {
    id: "beach",
    name: "Chaliyam Beach", mal: "ചാലിയം കടൽത്തീരം", tag: "Beach",
    bg: "linear-gradient(135deg,#006994,#00a8cc)",
    image: "https://picsum.photos/seed/chaliyambeach/600/400",
    lat: 11.1610, lng: 75.7980,
    desc: "A serene, less-crowded beach known for its calm waters and stunning sunset views over the Arabian Sea. Popular among local fishing families and nature lovers."
  },
  {
    id: "lighthouse",
    name: "Chaliyam Lighthouse", mal: "ദീപസ്തംഭം", tag: "Heritage",
    bg: "linear-gradient(135deg,#8b6310,#c9941a)",
    image: "https://picsum.photos/seed/lighthouse/600/400",
    lat: 11.1625, lng: 75.7995,
    desc: "The iconic lighthouse standing guard over the Beypore-Chaliyam coastline. Offers panoramic views of the Arabian Sea and the Kozhikode skyline."
  },
  {
    id: "rivermouth",
    name: "Chaliyar River Mouth", mal: "ചാലിയാർ നദീമുഖം", tag: "Nature",
    bg: "linear-gradient(135deg,#1a6b3c,#2d7a4f)",
    image: "https://picsum.photos/seed/rivermouth/600/400",
    lat: 11.1700, lng: 75.8080,
    desc: "Where the Chaliyar River meets the Arabian Sea — a breathtaking confluence popular for boat rides, backwater scenery and migratory bird watching."
  },
  {
    id: "mosque",
    name: "Old Chaliyam Mosque", mal: "ജുമാ മസ്ജിദ്", tag: "Heritage",
    bg: "linear-gradient(135deg,#1a4a2e,#3d7a5a)",
    image: "https://picsum.photos/seed/mosque/600/400",
    lat: 11.1655, lng: 75.8025,
    desc: "A historic mosque dating back several centuries, reflecting the rich Islamic heritage of Chaliyam. Known for its traditional Kerala-style architecture."
  },
  {
    id: "harbour",
    name: "Chaliyam Fishing Harbour", mal: "മൽസ്യബന്ധന തുറമുഖം", tag: "Culture",
    bg: "linear-gradient(135deg,#0d47a1,#1976d2)",
    image: "https://picsum.photos/seed/harbour/600/400",
    lat: 11.1645, lng: 75.7990,
    desc: "The lifeline of Chaliyam — a bustling fishing harbour where hundreds of boats set sail daily. Experience the authentic life of Kerala's fishing community."
  },
  {
    id: "walkway",
    name: "Beypore Beach Walkway", mal: "ബേപ്പൂർ ബീച്ച് വഴി", tag: "Scenic",
    bg: "linear-gradient(135deg,#e65100,#f57c00)",
    image: "https://picsum.photos/seed/walkway/600/400",
    lat: 11.1685, lng: 75.8015,
    desc: "A beautiful coastal walkway connecting Chaliyam to the famous Beypore beach, lined with palm trees and offering spectacular sea views along the way."
  },
  {
    id: "mangroves",
    name: "Chaliyam Mangrove Forest", mal: "കണ്ടൽ കാടുകൾ", tag: "Eco",
    bg: "linear-gradient(135deg,#2e7d32,#43a047)",
    image: "https://picsum.photos/seed/mangroves/600/400",
    lat: 11.1650, lng: 75.8010,
    desc: "A precious ecosystem of mangrove forests along the Chaliyar riverbanks. Home to diverse bird species and marine life — perfect for eco-tourism."
  },
  {
    id: "market",
    name: "Friday Market (Chantha)", mal: "ചന്ത", tag: "Market",
    bg: "linear-gradient(135deg,#6a1b9a,#8e24aa)",
    image: "https://picsum.photos/seed/market/600/400",
    lat: 11.1675, lng: 75.8050,
    desc: "The vibrant weekly market is the social heart of Chaliyam. Fresh fish, vegetables, spices and local produce — a true Kerala market experience."
  },
  {
    id: "jetty",
    name: "Chaliyam Boat Jetty", mal: "ബോട്ട് ജെട്ടി", tag: "Transport",
    bg: "linear-gradient(135deg,#00695c,#00897b)",
    image: "https://picsum.photos/seed/jetty/600/400",
    lat: 11.1660, lng: 75.8040,
    desc: "The traditional boat jetty connecting Chaliyam to Beypore. Passengers can enjoy a scenic short ferry ride across the Chaliyar river mouth."
  },
  {
    id: "temple",
    name: "Thoovapara Temple", mal: "തൂവപ്പാറ ക്ഷേത്രം", tag: "Heritage",
    bg: "linear-gradient(135deg,#b71c1c,#e53935)",
    image: "https://picsum.photos/seed/temple/600/400",
    lat: 11.1695, lng: 75.8035,
    desc: "An ancient temple with deep roots in Chaliyam's cultural heritage. Known for its traditional festivals, especially the annual theyyam performances."
  }
];

export const BUS_DATA = [
  { time: "05:30", name: "Chaliyam Express", route: "kozhikode", dest: "Kozhikode Bus Stand", via: "Beypore, Pavangad", freq: "Once", stops: ["Chaliyam", "Beypore", "Meenchanda", "Kozhikode"] },
  { time: "06:00", name: "Beypore Service", route: "beypore", dest: "Beypore Junction", via: "Direct", freq: "Daily", stops: ["Chaliyam", "Boat Jetty", "Beypore"] },
  { time: "06:15", name: "City Connect", route: "kozhikode", dest: "Kozhikode City", via: "Feroke, Pavangad", freq: "Weekdays", stops: ["Chaliyam", "Feroke", "Kozhikode"] },
  { time: "06:45", name: "Feroke Shuttle", route: "feroke", dest: "Feroke Town", via: "Direct", freq: "Daily", stops: ["Chaliyam", "Karuvanthiruthi", "Feroke"] },
  { time: "07:00", name: "Chaliyam–Calicut", route: "calicut", dest: "Calicut Beach", via: "Beypore, SM Street", freq: "Daily", stops: ["Chaliyam", "Beypore", "SM Street", "Beach"] },
  { time: "07:30", name: "Morning Express", route: "kozhikode", dest: "Kozhikode Bus Stand", via: "Pavangad", freq: "Daily", stops: ["Chaliyam", "Meenchanda", "Kozhikode"] },
  { time: "08:00", name: "Beypore Ordinary", route: "beypore", dest: "Beypore Junction", via: "Chaliyam Road", freq: "Daily", stops: ["Chaliyam", "Beypore"] },
  { time: "08:30", name: "Kozhikode Fast", route: "kozhikode", dest: "Kozhikode City", via: "Feroke", freq: "Daily", stops: ["Chaliyam", "Feroke", "Kozhikode"] },
  { time: "09:00", name: "Feroke Service", route: "feroke", dest: "Feroke Town", via: "Beypore", freq: "Daily", stops: ["Chaliyam", "Beypore", "Feroke"] },
  { time: "09:30", name: "Beach Route", route: "calicut", dest: "Calicut Beach", via: "Pavangad", freq: "Daily", stops: ["Chaliyam", "Beach"] },
  { time: "10:00", name: "Mid Morning Express", route: "kozhikode", dest: "Kozhikode Bus Stand", via: "Direct", freq: "Daily", stops: ["Chaliyam", "Kozhikode"] },
  { time: "11:00", name: "Feroke Link", route: "feroke", dest: "Feroke Town", via: "Direct", freq: "Mon-Sat", stops: ["Chaliyam", "Feroke"] },
  { time: "12:00", name: "Noon Service", route: "kozhikode", dest: "Kozhikode City", via: "Pavangad", freq: "Daily", stops: ["Chaliyam", "Kozhikode"] },
  { time: "13:00", name: "Afternoon Beypore", route: "beypore", dest: "Beypore Junction", via: "Direct", freq: "Daily", stops: ["Chaliyam", "Beypore"] },
  { time: "14:00", name: "City Express", route: "kozhikode", dest: "Kozhikode Bus Stand", via: "Feroke", freq: "Daily", stops: ["Chaliyam", "Feroke", "Kozhikode"] },
  { time: "15:30", name: "Evening Feroke", route: "feroke", dest: "Feroke Town", via: "Beypore", freq: "Daily", stops: ["Chaliyam", "Beypore", "Feroke"] },
  { time: "16:00", name: "Beach Evening", route: "calicut", dest: "Calicut Beach", via: "SM Street", freq: "Daily", stops: ["Chaliyam", "SM Street", "Beach"] },
  { time: "17:00", name: "Evening Express", route: "kozhikode", dest: "Kozhikode Bus Stand", via: "Pavangad", freq: "Daily", stops: ["Chaliyam", "Kozhikode"] },
  { time: "18:30", name: "Last Beypore", route: "beypore", dest: "Beypore Junction", via: "Direct", freq: "Daily", stops: ["Chaliyam", "Beypore"] },
  { time: "20:00", name: "Night Service", route: "kozhikode", dest: "Kozhikode City", via: "Feroke", freq: "Daily", stops: ["Chaliyam", "Feroke", "Kozhikode"] },
];

export const EMERGENCY = [
  { name: "Chaliyam Police", sub: "Chaliyam Police Station", number: "0495-2480100", alt: "100", type: "police", category: "Police" },
  { name: "Ambulance", sub: "Emergency Ambulance Service", number: "108", alt: "1800-425-1010", type: "ambulance", category: "Medical" },
  { name: "Beypore Govt. Hospital", sub: "Nearest Government Hospital", number: "0495-2411234", alt: "", type: "hospital", category: "Medical" },
  { name: "Fire Force", sub: "Kerala Fire & Rescue Services", number: "101", alt: "0495-2720100", type: "fire", category: "Fire" },
  { name: "Coast Guard", sub: "Indian Coast Guard Kozhikode", number: "0495-2368484", alt: "1554", type: "coast", category: "Marine" },
  { name: "National Emergency", sub: "Single Emergency Number", number: "112", alt: "", type: "ambulance", category: "Emergency" },
  { name: "Women Helpline", sub: "Kerala Women Commission", number: "1800-425-1733", alt: "181", type: "women", category: "Women" },
  { name: "Child Helpline", sub: "Childline India Foundation", number: "1098", alt: "", type: "hospital", category: "Children" },
  { name: "Chaliyam Panchayat", sub: "Gram Panchayat Office", number: "0495-2480200", alt: "", type: "coast", category: "Govt" },
  { name: "KSEB Helpline", sub: "Electricity Emergency", number: "1912", alt: "0495-2720400", type: "fire", category: "Utility" },
  { name: "Water Authority", sub: "Kerala Water Authority", number: "1800-425-0340", alt: "", type: "coast", category: "Utility" },
  { name: "Medical Helpline", sub: "Health Emergency Kerala", number: "104", alt: "", type: "hospital", category: "Medical" }
];

export const DIRECTORY = [
  { id: "dir1", name: "New World Gym", cat: "service", catLabel: "Services", desc: "A premium gym and fitness center equipped with modern workout equipment. Items: Pending data collection.", rating: 4.8, reviews: 45, image: "https://picsum.photos/seed/dir1/600/400", mapUrl: "https://maps.app.goo.gl/8PY7wGvUiZj4Wmde8" },
  { id: "dir2", name: "Leather world", cat: "retail", catLabel: "Retail", desc: "Your one-stop destination for footwear, lifestyle products, and fancy gift items. Items: Pending data collection.", rating: 4.5, reviews: 32, image: "https://picsum.photos/seed/dir2/600/400", mapUrl: "https://maps.app.goo.gl/ANFhwTR5DNXMCvWr6" },
  { id: "dir3", name: "Beevis Supermarket", cat: "retail", catLabel: "Retail", desc: "A well-stocked supermarket offering a wide variety of groceries and daily essentials. Items: Pending data collection.", rating: 4.6, reviews: 88, image: "https://picsum.photos/seed/dir3/600/400", mapUrl: "https://maps.app.goo.gl/HwVixKiCPw3cw7129" },
  { id: "dir4", name: "Bhartiya jan aushadhi kendra", cat: "medical", catLabel: "Medical", desc: "Providing high-quality generic medicines and medical supplies at affordable price. Items: Pending data collection.", rating: 4.9, reviews: 110, image: "https://picsum.photos/seed/dir4/600/400", mapUrl: "https://maps.app.goo.gl/hPuuURzgDcP6wV6a8" },
  { id: "dir5", name: "Shaar chickens", cat: "retail", catLabel: "Retail", desc: "Fresh chicken and quality meat products stall for your daily needs. Items: Pending data collection.", rating: 4.4, reviews: 29, image: "https://picsum.photos/seed/dir5/600/400", mapUrl: "https://maps.app.goo.gl/eu6NDgXhjQZLSUxN8" },
  { id: "dir6", name: "Fedex stationery", cat: "retail", catLabel: "Retail", desc: "Local stationery shop offering a variety of school, office supplies, and daily items. Items: Pending data collection.", rating: 4.2, reviews: 15, image: "https://picsum.photos/seed/dir6/600/400", mapUrl: "https://maps.app.goo.gl/ns3gUtAHAtddhEqM6" },
  { id: "dir7", name: "Beauty Center", cat: "retail", catLabel: "Retail", desc: "Quality fancy items, footwear, lifestyle goods, and beautiful gift products. Items: Pending data collection.", rating: 4.5, reviews: 50, image: "https://picsum.photos/seed/dir7/600/400", mapUrl: "https://maps.app.goo.gl/ANFhwTR5DNXMCvWr6" },
  { id: "dir8", name: "Hotel safa", cat: "food", catLabel: "Food", desc: "Delicious local street food and traditional meals served fresh daily. Items: Pending data collection.", rating: 4.7, reviews: 140, image: "https://picsum.photos/seed/dir8/600/400", mapUrl: "https://maps.app.goo.gl/259UQcxP9GuU3fkk7" },
  { id: "dir9", name: "Chaliyam Medicals", cat: "medical", catLabel: "Medical", desc: "Trusted local medical store delivering essential medicines and healthcare products. Items: Pending data collection.", rating: 4.8, reviews: 92, image: "https://picsum.photos/seed/dir9/600/400", mapUrl: "https://maps.app.goo.gl/13b7dHK8yH9xQ1BT9" },
  { id: "dir10", name: "Shaliyathi Supermarket", cat: "retail", catLabel: "Retail", desc: "Your community supermarket for groceries, fruits, vegetables, and household goods. Items: Pending data collection.", rating: 4.3, reviews: 60, image: "https://picsum.photos/seed/dir10/600/400", mapUrl: "https://maps.app.goo.gl/PAnZYeb3EZduFrjK6" },
  { id: "dir11", name: "Mubarak coolbar", cat: "food", catLabel: "Food", desc: "Refreshing localized cool bar, fresh juices, and authentic milma dairy products. Items: Pending data collection.", rating: 4.5, reviews: 45, image: "https://picsum.photos/seed/dir11/600/400", mapUrl: "https://maps.app.goo.gl/4TxGvkefQyHHNHpu5" },
  { id: "dir12", name: "Cool palace", cat: "food", catLabel: "Food", desc: "Fresh assorted fruits and a variety of cooling refreshing drinks. Items: Pending data collection.", rating: 4.6, reviews: 33, image: "https://picsum.photos/seed/dir12/600/400", mapUrl: "https://maps.app.goo.gl/KwDYcLvpqLqszMU3A" },
  { id: "dir13", name: "Anan store", cat: "retail", catLabel: "Retail", desc: "A comprehensive local store offering day-to-day items and groceries. Items: Pending data collection.", rating: 4.1, reviews: 18, image: "https://picsum.photos/seed/dir13/600/400", mapUrl: "https://maps.app.goo.gl/b9DeveNLsnqJR1Yp7" },
  { id: "dir14", name: "Muslim league office", cat: "service", catLabel: "Services", desc: "Local community representation and Muslim League party coordination office.", rating: 4.0, reviews: 11, image: "https://picsum.photos/seed/dir14/600/400", mapUrl: "https://maps.app.goo.gl/iwbcCs85cNh2rUbf9" },
  { id: "dir15", name: "Choice bakery", cat: "food", catLabel: "Food", desc: "Freshly baked cakes, sweet treats, and a relaxing cool bar for snacking. Items: Pending data collection.", rating: 4.7, reviews: 85, image: "https://picsum.photos/seed/dir15/600/400", mapUrl: "https://maps.app.goo.gl/tGjwvR5mAj1Q4D8HA" },
  { id: "dir16", name: "Lensman studio", cat: "service", catLabel: "Services", desc: "Professional photography, portrait shoots, and camera studio services. Items: Pending data collection.", rating: 4.9, reviews: 26, image: "https://picsum.photos/seed/dir16/600/400", mapUrl: "https://maps.app.goo.gl/MWet7y4iajBR85Z18" },
  { id: "dir17", name: "Badriya chicken stall", cat: "retail", catLabel: "Retail", desc: "Hygienic and fresh chicken stall providing daily cut meat products. Items: Pending data collection.", rating: 4.2, reviews: 21, image: "https://picsum.photos/seed/dir17/600/400", mapUrl: "https://maps.app.goo.gl/jxrfoPoDNrSJZCYv9" },
  { id: "dir18", name: "Thalassery cafe", cat: "food", catLabel: "Food", desc: "Authentic Thalassery-style tea, snacks, and a cozy cool bar for evening bites. Items: Pending data collection.", rating: 4.8, reviews: 112, image: "https://picsum.photos/seed/dir18/600/400", mapUrl: "https://maps.app.goo.gl/1uJcUSrsfoekyz818" },
  { id: "dir19", name: "Ayisha’s bakery", cat: "food", catLabel: "Food", desc: "A traditional bakery known for custom cakes, pastries, and fresh baked goods. Items: Pending data collection.", rating: 4.6, reviews: 54, image: "https://picsum.photos/seed/dir19/600/400", mapUrl: "https://maps.app.goo.gl/4pfpyb7m3VCxqv4w5" },
  { id: "dir20", name: "Rafa gifts", cat: "retail", catLabel: "Retail", desc: "Excellent collection of lifestyle accessories, footwear, and perfect gift choices. Items: Pending data collection.", rating: 4.4, reviews: 30, image: "https://picsum.photos/seed/dir20/600/400", mapUrl: "https://maps.app.goo.gl/z6YbmF9ZpKLFxNDk9" },
  { id: "dir21", name: "FM Fancy", cat: "retail", catLabel: "Retail", desc: "A premium outlet for all your fancy accessories, footwear, and lifestyle needs. Items: Pending data collection.", rating: 4.3, reviews: 22, image: "https://picsum.photos/seed/dir21/600/400", mapUrl: "https://maps.app.goo.gl/oY9C3iEXDSfQTVi39" },
  { id: "dir22", name: "Tasty hut", cat: "food", catLabel: "Food", desc: "Popular local hotel serving extremely tasty traditional and modern food. Items: Pending data collection.", rating: 4.6, reviews: 90, image: "https://picsum.photos/seed/dir22/600/400", mapUrl: "https://maps.app.goo.gl/Y4UifKZoLszPRHyc9" },
  { id: "dir23", name: "Breeze pharma", cat: "medical", catLabel: "Medical", desc: "Reliable pharmacy with a wide range of prescription and over-the-counter medicines. Items: Pending data collection.", rating: 4.7, reviews: 45, image: "https://picsum.photos/seed/dir23/600/400", mapUrl: "https://maps.app.goo.gl/zeLNRL4wqdWBJDmc9" },
  { id: "dir24", name: "PK fruits", cat: "retail", catLabel: "Retail", desc: "Fresh seasonal fruits, dry fruits, and healthy selections straight from the market. Items: Pending data collection.", rating: 4.5, reviews: 37, image: "https://picsum.photos/seed/dir24/600/400", mapUrl: "https://maps.app.goo.gl/2Cxpb5LRA7ohmcb58" },
  { id: "dir25", name: "Sweet world", cat: "food", catLabel: "Food", desc: "A paradise for sweet lovers combining a traditional bakery with a refreshing coolbar. Items: Pending data collection.", rating: 4.6, reviews: 62, image: "https://picsum.photos/seed/dir25/600/400", mapUrl: "https://maps.app.goo.gl/cs5UwhURiMiwp4Gk6" },
  { id: "dir26", name: "Amana jewelry", cat: "retail", catLabel: "Retail", desc: "Beautiful traditional and contemporary gold jewelry collections for all occasions. Items: Pending data collection.", rating: 4.8, reviews: 75, image: "https://picsum.photos/seed/dir26/600/400", mapUrl: "https://maps.app.goo.gl/2i9Yh95JgpJqyjvt6" },
  { id: "dir27", name: "Foxcon cafe", cat: "service", catLabel: "Services", desc: "Your local digital printing, internet browsing, and reprography hub. Items: Pending data collection.", rating: 4.2, reviews: 19, image: "https://picsum.photos/seed/dir27/600/400", mapUrl: "https://maps.app.goo.gl/kchDzGSfQENKktsRA" },
  { id: "dir28", name: "E Digital", cat: "retail", catLabel: "Retail", desc: "Latest mobile phones, accessories, hardware repairs, and digital services. Items: Pending data collection.", rating: 4.5, reviews: 52, image: "https://picsum.photos/seed/dir28/600/400", mapUrl: "https://maps.app.goo.gl/ZA7kNSPeUvi6a1b4A" },
  { id: "dir29", name: "NHIMS", cat: "service", catLabel: "Services", desc: "Comprehensive tour packages, ticketing, and dedicated travel services. Items: Pending data collection.", rating: 4.6, reviews: 24, image: "https://picsum.photos/seed/dir29/600/400", mapUrl: "https://maps.app.goo.gl/SjeqBLfJL9rGYcuq9" },
  { id: "dir30", name: "PT fishing net", cat: "fishing", catLabel: "Fishing", desc: "Wholesale and retail supplier of top-quality fishing nets and marine equipment. Items: Pending data collection.", rating: 4.7, reviews: 31, image: "https://picsum.photos/seed/dir30/600/400", mapUrl: "https://maps.app.goo.gl/P5PKhnWXwK4QywMP9" },
  { id: "dir31", name: "AutoRickshaw stant", cat: "transport", catLabel: "Transport", desc: "The main point for local auto-rickshaw transport services within the village.", rating: 4.3, reviews: 40, image: "https://picsum.photos/seed/dir31/600/400", mapUrl: "https://maps.app.goo.gl/pfn4G9xNK527MmV98" },
  { id: "dir32", name: "Brains Tution center (8th to 9th standard)", cat: "education", catLabel: "Education", desc: "Dedicated academic coaching for 8th and 9th standard students. Items: Pending data collection.", rating: 4.8, reviews: 66, image: "https://picsum.photos/seed/dir32/600/400", mapUrl: "https://maps.app.goo.gl/rt7p9sMmPyMheX5v9" },
  { id: "dir33", name: "Brains Tution center (10th standard)", cat: "education", catLabel: "Education", desc: "Focused 10th standard board exam preparatory tuition center. Items: Pending data collection.", rating: 4.9, reviews: 82, image: "https://picsum.photos/seed/dir33/600/400", mapUrl: "https://maps.app.goo.gl/fxUPxdwCZQzYfqvf7" },
  { id: "dir34", name: "Bismi supermarket", cat: "retail", catLabel: "Retail", desc: "Modern supermarket with a huge inventory of daily groceries and household items. Items: Pending data collection.", rating: 4.5, reviews: 74, image: "https://picsum.photos/seed/dir34/600/400", mapUrl: "https://maps.app.goo.gl/DYQGgpMGfxHtgbDu6" },
  { id: "dir35", name: "Sainas textiles", cat: "retail", catLabel: "Retail", desc: "Trendy clothing, traditional wear, and fabric collections for the whole family. Items: Pending data collection.", rating: 4.6, reviews: 55, image: "https://picsum.photos/seed/dir35/600/400", mapUrl: "https://maps.app.goo.gl/fxUPxdwCZQzYfqvf7" },
  { id: "dir36", name: "Trust online services - csc", cat: "service", catLabel: "Services", desc: "Authorized CSC center for government online services, printing, and ticketing. Items: Pending data collection.", rating: 4.4, reviews: 36, image: "https://picsum.photos/seed/dir36/600/400", mapUrl: "https://maps.app.goo.gl/fVHKJmYB54iipDyE6" },
  { id: "dir37", name: "Kadalundi Service sahakarana bank", cat: "finance", catLabel: "Finance", desc: "Local cooperative bank serving the financial and saving needs of the community. Items: Pending data collection.", rating: 4.5, reviews: 48, image: "https://picsum.photos/seed/dir37/600/400", mapUrl: "https://maps.app.goo.gl/GkFr4zHVNXqidW5f9" },
  { id: "dir38", name: "KN digital Hub", cat: "retail", catLabel: "Retail", desc: "A prime destination for cell phone repair, accessories, and digital gadgets. Items: Pending data collection.", rating: 4.3, reviews: 29, image: "https://picsum.photos/seed/dir38/600/400", mapUrl: "https://maps.app.goo.gl/VSvsZKX5TvVy7Wrx7" },
  { id: "dir39", name: "Shahalas center", cat: "retail", catLabel: "Retail", desc: "Exclusive lifestyle store featuring fancy footwear, daily fashion, and gifts. Items: Pending data collection.", rating: 4.4, reviews: 41, image: "https://picsum.photos/seed/dir39/600/400", mapUrl: "https://maps.app.goo.gl/VSvsZKX5TvVy7Wrx7" },
  { id: "dir40", name: "Edu Vibe tuition center", cat: "education", catLabel: "Education", desc: "Empowering students through excellent supplementary education and coaching. Items: Pending data collection.", rating: 4.7, reviews: 58, image: "https://picsum.photos/seed/dir40/600/400", mapUrl: "https://maps.app.goo.gl/bgt5LnzjTQQT9398A" },
  { id: "dir41", name: "Mythri Medicals", cat: "medical", catLabel: "Medical", desc: "Community-friendly pharmacy delivering essential healthcare and medicinal products. Items: Pending data collection.", rating: 4.6, reviews: 47, image: "https://picsum.photos/seed/dir41/600/400", mapUrl: "https://maps.app.goo.gl/k8LuVuFPo5dBgfo37" },
  { id: "dir42", name: "Cake N Treat", cat: "food", catLabel: "Food", desc: "Specialty cakes, bakes, and delightful sweet treats for celebrations. Items: Pending data collection.", rating: 4.8, reviews: 88, image: "https://picsum.photos/seed/dir42/600/400", mapUrl: "https://maps.app.goo.gl/nUXPrbws8umrbwXK7" },
  { id: "dir43", name: "Dr. Rinsina’s homeo speciality clinic", cat: "medical", catLabel: "Medical", desc: "Expert homeopathic consultations and advanced specialty care clinic. Items: Pending data collection.", rating: 4.9, reviews: 62, image: "https://picsum.photos/seed/dir43/600/400", mapUrl: "https://maps.app.goo.gl/daUrBqiYx7Wnf1UH6" },
  { id: "dir44", name: "Manglodayam vaydyashala", cat: "medical", catLabel: "Medical", desc: "Authentic Ayurvedic medicines, herbal treatments, and wellness products. Items: Pending data collection.", rating: 4.7, reviews: 44, image: "https://picsum.photos/seed/dir44/600/400", mapUrl: "https://maps.app.goo.gl/38kBiUF4XnMjHYyF8" },
  { id: "dir45", name: "E Mithram", cat: "service", catLabel: "Services", desc: "Common service center for fast online applications, printing, and digital tasks. Items: Pending data collection.", rating: 4.5, reviews: 33, image: "https://picsum.photos/seed/dir45/600/400", mapUrl: "https://maps.app.goo.gl/sUcEBXdpHLwMs6Kj6" },
  { id: "dir46", name: "Sidheeq jumah masjid", cat: "religious", catLabel: "Religious", desc: "A peaceful place of worship and congregational prayers for the local community.", rating: 4.9, reviews: 120, image: "https://picsum.photos/seed/dir46/600/400", mapUrl: "https://maps.app.goo.gl/oEK9oxf9fhUMs7EfA" },
  { id: "dir47", name: "Thavakkal store", cat: "retail", catLabel: "Retail", desc: "Reliable neighborhood supermarket supplying groceries, snacks, and home essentials. Items: Pending data collection.", rating: 4.4, reviews: 26, image: "https://picsum.photos/seed/dir47/600/400", mapUrl: "https://maps.app.goo.gl/a7rKo6MniSW1C66h6" },
  { id: "dir48", name: "Chaliyam city masjid", cat: "religious", catLabel: "Religious", desc: "A central and prominent Masjid situated right in the heart of Chaliyam.", rating: 4.9, reviews: 155, image: "https://picsum.photos/seed/dir48/600/400", mapUrl: "https://maps.app.goo.gl/VAbhm3P5MT5XZNRe8" },
  { id: "dir49", name: "Ajmal printers", cat: "service", catLabel: "Services", desc: "Professional offset and digital printing services for books, banners, and cards. Items: Pending data collection.", rating: 4.6, reviews: 40, image: "https://picsum.photos/seed/dir49/600/400", mapUrl: "https://maps.app.goo.gl/Hj2QrdHMNPHpJvxH7" },
  { id: "dir50", name: "Anam's stationery Near UHHSS", cat: "retail", catLabel: "Retail", desc: "Stationery and essential student supplies store conveniently located near UHHSS. Items: Pending data collection.", rating: 4.3, reviews: 22, image: "https://picsum.photos/seed/dir50/600/400", mapUrl: "https://maps.app.goo.gl/MRwPuuDCrZWgMtDo7" },
  { id: "dir51", name: "Bharaka", cat: "food", catLabel: "Food", desc: "Your go-to coolbar and refreshing tea shop for a quick daily break. Items: Pending data collection.", rating: 4.6, reviews: 59, image: "https://picsum.photos/seed/dir51/600/400", mapUrl: "https://maps.app.goo.gl/A6q2Fd8KWVSRg1Fk9" },
  { id: "dir52", name: "Chaliyam Harbour", cat: "fishing", catLabel: "Fishing", desc: "The bustling wholesale fish market and harbor offering fresh daily ocean catches. Items: Pending data collection.", rating: 4.8, reviews: 200, image: "https://picsum.photos/seed/dir52/600/400", mapUrl: "https://maps.app.goo.gl/6JXFLsv6XGBpBGKM8" },
  { id: "dir53", name: "Chaliyam pertroliam", cat: "retail", catLabel: "Retail", desc: "Hindustan Petroleum station offering clean fuel and vehicle support services. Items: Pending data collection.", rating: 4.5, reviews: 110, image: "https://picsum.photos/seed/dir53/600/400", mapUrl: "https://maps.app.goo.gl/2CR2a3jYBvLmzQLD8" },
  { id: "dir54", name: "Cheriya palli near yaaram maqam", cat: "religious", catLabel: "Religious", desc: "A historic and spiritually significant small masjid near Yaaram Maqam.", rating: 4.8, reviews: 86, image: "https://picsum.photos/seed/dir54/600/400", mapUrl: "https://maps.app.goo.gl/uY4c8HthrHFXX5kZA" },
  { id: "dir55", name: "Hortus malabaricus", cat: "education", catLabel: "Education", desc: "A lush botanical garden preserving native flora and offering ecological education.", rating: 4.7, reviews: 64, image: "https://picsum.photos/seed/dir55/600/400", mapUrl: "https://maps.app.goo.gl/sQDBSbK2ZQbEFx9n7" },
  { id: "dir56", name: "Govt. Timbar Depot Chaliyam", cat: "service", catLabel: "Services", desc: "Official government timber depot supplying quality, regulated wood resources.", rating: 4.2, reviews: 33, image: "https://picsum.photos/seed/dir56/600/400", mapUrl: "https://maps.app.goo.gl/Htt1dnnLrkzjuEXe9" },
  { id: "dir57", name: "Fathimabi memorial Trust", cat: "service", catLabel: "Services", desc: "A spacious auditorium perfect for hosting local weddings and community events. Items: Pending data collection.", rating: 4.5, reviews: 75, image: "https://picsum.photos/seed/dir57/600/400", mapUrl: "https://maps.app.goo.gl/yy3AX5qJrcdQVm7c7" },
  { id: "dir58", name: "Federal Bank (chaliyam branch)", cat: "finance", catLabel: "Finance", desc: "Dedicated Chaliyam branch of the Federal Bank for all modern banking facilities. Items: Pending data collection.", rating: 4.4, reviews: 92, image: "https://picsum.photos/seed/dir58/600/400", mapUrl: "https://maps.app.goo.gl/Br3UNm5938r2mbcq5" },
  { id: "dir59", name: "Kadalundi co-operative urban society", cat: "finance", catLabel: "Finance", desc: "A robust cooperative urban society supporting local financial empowerment. Items: Pending data collection.", rating: 4.6, reviews: 52, image: "https://picsum.photos/seed/dir59/600/400", mapUrl: "https://maps.app.goo.gl/noKr4HNjJWvNh4pz5" },
  { id: "dir60", name: "Kaithavalapu anganwadi", cat: "education", catLabel: "Education", desc: "Nurturing early childhood education center and pre-school facility. Items: Pending data collection.", rating: 4.7, reviews: 40, image: "https://picsum.photos/seed/dir60/600/400", mapUrl: "https://maps.app.goo.gl/75bhWmDZ1mB24M3v8" },
  { id: "dir61", name: "Koya’s trade link", cat: "retail", catLabel: "Retail", desc: "Top supplier of cement, construction hardware, and high-quality building materials. Items: Pending data collection.", rating: 4.5, reviews: 36, image: "https://picsum.photos/seed/dir61/600/400", mapUrl: "https://maps.app.goo.gl/Hj2QrdHMNPHpJvxH7" },
  { id: "dir62", name: "KP dental", cat: "medical", catLabel: "Medical", desc: "Expert dental clinic providing comprehensive oral care and hygiene treatments. Items: Pending data collection.", rating: 4.8, reviews: 68, image: "https://picsum.photos/seed/dir62/600/400", mapUrl: "https://maps.app.goo.gl/Hj2QrdHMNPHpJvxH7" },
  { id: "dir63", name: "Madrasathul manar college - ALmiac", cat: "education", catLabel: "Education", desc: "A respected local educational institution focusing on higher academic excellence. Items: Pending data collection.", rating: 4.6, reviews: 88, image: "https://picsum.photos/seed/dir63/600/400", mapUrl: "https://maps.app.goo.gl/ZxLDwePFbQ1YZWLE6" },
  { id: "dir64", name: "Majid Al Mujahideen, Salafi Masjid", cat: "religious", catLabel: "Religious", desc: "A serene Salafi masjid aimed at spiritual guidance and congregational worship.", rating: 4.9, reviews: 105, image: "https://picsum.photos/seed/dir64/600/400", mapUrl: "https://maps.app.goo.gl/zSfSLnZ821SDPsb67" },
  { id: "dir65", name: "Masjid AL mujahideen, salafi masjid parking area", cat: "service", catLabel: "Services", desc: "Spacious open parking area for congregants attached to the Salafi Masjid.", rating: 4.5, reviews: 29, image: "https://picsum.photos/seed/dir65/600/400", mapUrl: "https://maps.app.goo.gl/be7KEFntzky7mACJA" },
  { id: "dir66", name: "Minor foods near bharaka", cat: "food", catLabel: "Food", desc: "A cozy local spot for tea and small everyday hotel meals. Items: Pending data collection.", rating: 4.6, reviews: 43, image: "https://picsum.photos/seed/dir66/600/400", mapUrl: "https://maps.app.goo.gl/mmcRPt7QsaUi9QcJA" },
  { id: "dir67", name: "MMLP School, Chaliyam", cat: "education", catLabel: "Education", desc: "A foundational Malayalam Medium Lower Primary school for local kids. Items: Pending data collection.", rating: 4.7, reviews: 75, image: "https://picsum.photos/seed/dir67/600/400", mapUrl: "https://maps.app.goo.gl/nx9A4GamJk36cxen8" },
  { id: "dir68", name: "Monbatha palli", cat: "religious", catLabel: "Religious", desc: "Prominent local praying facility honoring Islamic traditions and daily worship.", rating: 4.8, reviews: 130, image: "https://picsum.photos/seed/dir68/600/400", mapUrl: "https://maps.app.goo.gl/H29NzSEeGN9XabPY8" },
  { id: "dir69", name: "Nellikkavil Graveyard", cat: "religious", catLabel: "Religious", desc: "The historical and primary Muslim resting place/graveyard for the community.", rating: 4.7, reviews: 55, image: "https://picsum.photos/seed/dir69/600/400", mapUrl: "https://maps.app.goo.gl/TD4s8Ccj4W4nSVfZ9" },
  { id: "dir70", name: "New shifa speciality clinic", cat: "medical", catLabel: "Medical", desc: "Modern medical specialty clinic featuring advanced diagnostic and doctor consultations. Items: Pending data collection.", rating: 4.8, reviews: 67, image: "https://picsum.photos/seed/dir70/600/400", mapUrl: "https://maps.app.goo.gl/Br3UNm5938r2mbcq5" },
  { id: "dir71", name: "Noorudheen sheikh maqam", cat: "religious", catLabel: "Religious", desc: "A historically rich Islamic Maqam and adjoining masjid for spiritual visitors.", rating: 4.9, reviews: 145, image: "https://picsum.photos/seed/dir71/600/400", mapUrl: "https://maps.app.goo.gl/zByYG1dAAqth1Ti9A" },
  { id: "dir72", name: "ORCHID (stationery and bunk shop) Near UHHSS", cat: "retail", catLabel: "Retail", desc: "High-quality stationery and bunk shop conveniently situated near UHHSS. Items: Pending data collection.", rating: 4.4, reviews: 31, image: "https://picsum.photos/seed/dir72/600/400", mapUrl: "https://maps.app.goo.gl/u2Nn9GfXLbhDUpC18" },
  { id: "dir73", name: "PBM English medium school", cat: "education", catLabel: "Education", desc: "A premier English medium school focused on holistic student development. Items: Pending data collection.", rating: 4.8, reviews: 110, image: "https://picsum.photos/seed/dir73/600/400", mapUrl: "https://maps.app.goo.gl/ezNkFZnWFmTD1CpH9" },
  { id: "dir74", name: "Bunk shop Near Monbatha palli", cat: "retail", catLabel: "Retail", desc: "A convenient local bunk shop for quick bites, snacks, and daily essentials. Items: Pending data collection.", rating: 4.2, reviews: 18, image: "https://picsum.photos/seed/dir74/600/400", mapUrl: "https://maps.app.goo.gl/9MoCi7vY1E1tbbLj6" },
  { id: "dir75", name: "Bunk shop near UHHSS", cat: "retail", catLabel: "Retail", desc: "Compact bunk shop offering student-friendly snacks and drinks near the school. Items: Pending data collection.", rating: 4.3, reviews: 26, image: "https://picsum.photos/seed/dir75/600/400", mapUrl: "https://maps.app.goo.gl/ECF6DdyRDHCHhcww7" },
  { id: "dir76", name: "Bunk shop Near PBM School", cat: "retail", catLabel: "Retail", desc: "Local bunk shop serving students and locals living in the PBM school vicinity. Items: Pending data collection.", rating: 4.3, reviews: 22, image: "https://picsum.photos/seed/dir76/600/400", mapUrl: "https://maps.app.goo.gl/ECF6DdyRDHCHhcww7" },
  { id: "dir77", name: "Stationery and Tea stall Near Federal Bank", cat: "retail", catLabel: "Retail", desc: "A hybrid stall near Federal Bank offering both office stationery and hot tea. Items: Pending data collection.", rating: 4.5, reviews: 39, image: "https://picsum.photos/seed/dir77/600/400", mapUrl: "https://maps.app.goo.gl/Br3UNm5938r2mbcq5" },
  { id: "dir78", name: "Tea Shop Near Chaliyam Harbour", cat: "food", catLabel: "Food", desc: "Early-opening tea shop serving hardworking fishermen directly at the harbour. Items: Pending data collection.", rating: 4.8, reviews: 85, image: "https://picsum.photos/seed/dir78/600/400", mapUrl: "https://maps.app.goo.gl/bbZs7h46ohn1c5nb8" },
  { id: "dir79", name: "UMBICHI HAJI HIGHER SECONDARY SCHOOL-UHHSS", cat: "education", catLabel: "Education", desc: "Leading Higher Secondary Education institution offering diverse streams and coaching. Items: Pending data collection.", rating: 4.8, reviews: 140, image: "https://picsum.photos/seed/dir79/600/400", mapUrl: "https://maps.app.goo.gl/MRwPuuDCrZWgMtDo7" },
  { id: "dir80", name: "Veluson’s Metal Industries", cat: "service", catLabel: "Services", desc: "Robust metal fabrication and industrial engineering solutions provider. Items: Pending data collection.", rating: 4.6, reviews: 37, image: "https://picsum.photos/seed/dir80/600/400", mapUrl: "https://maps.app.goo.gl/pU8hAAe4p3cqDo6T9" },
  { id: "dir81", name: "Yaaram Bus Stop", cat: "transport", catLabel: "Transport", desc: "Key transit knot and waiting shed connecting local transport vectors.", rating: 4.3, reviews: 55, image: "https://picsum.photos/seed/dir81/600/400", mapUrl: "https://maps.app.goo.gl/nGNb5Br2j6ECoUfn6" },
  { id: "dir82", name: "KP Foundation", cat: "service", catLabel: "Services", desc: "A forward-thinking local business enterprise and foundational corporate office. Items: Pending data collection.", rating: 4.7, reviews: 42, image: "https://picsum.photos/seed/dir82/600/400", mapUrl: "https://maps.app.goo.gl/DXVqhWgnDF6ZHoGr7" }
];

export const NEWS = [
  { type: "Event", date: "Mar 28, 2026", eventDate: "2026-04-15", title: "Chaliyam Fishermen's Day Festival", desc: "Annual celebration honoring the fishing community. Cultural programs, fish auction, and special prayer ceremony at the harbour from 4 PM onwards.", image: "https://picsum.photos/seed/festival/600/400" },
  { type: "Notice", date: "Mar 25, 2026", eventDate: "2026-04-10", title: "VHSS Annual Day Celebration", desc: "Chaliyam Government VHSS annual day celebrations this Friday. Cultural performances by students, prize distribution ceremony by MLA.", image: "https://picsum.photos/seed/school/600/400" },
  { type: "News", date: "Mar 22, 2026", eventDate: "2026-03-22", title: "Mangrove Restoration Drive Success", desc: "Over 500 mangrove saplings planted along the Chaliyar riverbanks by local volunteers. The initiative aims to restore the ecosystem.", image: "https://picsum.photos/seed/mangrove/600/400" },
  { type: "Alert", date: "Mar 20, 2026", eventDate: "2026-03-20", title: "Road Work: Chaliyam–Beypore Road", desc: "PWD announces maintenance work on the main Chaliyam–Beypore road this week. Expect minor delays. Alternative route via beach road recommended.", image: "https://picsum.photos/seed/road/600/400" },
  { type: "Sports", date: "Mar 18, 2026", eventDate: "2026-04-05", title: "Chaliyam Football Tournament 2026", desc: "Annual inter-ward football tournament begins this weekend. 12 teams registered. Venue: Chaliyam Maidan. Entry free for spectators.", image: "https://picsum.photos/seed/football/600/400" },
  { type: "Govt", date: "Mar 15, 2026", eventDate: "2026-03-30", title: "Panchayat Ward Meeting", desc: "Monthly ward sabha meeting on March 30 at the Panchayat office. Citizens can raise local issues directly with ward members and officials.", image: "https://picsum.photos/seed/meeting/600/400" },
];

export const PEOPLE = [
  { name: "P. A. Mohammed Riyas", role: "MLA, Beypore Constituency", phone: "0495-2345678", image: "https://ui-avatars.com/api/?name=Mohammed+Riyas&background=0D8ABC&color=fff&size=200", category: "Govt", website: "https://kerala.gov.in" },
  { name: "K. V. Safiya", role: "Ward Member", phone: "+91 98765 43210", image: "https://ui-avatars.com/api/?name=Safiya&background=4CAF50&color=fff&size=200", category: "Govt", website: "https://lsgkerala.gov.in" },
  { name: "Ramesh Kumar", role: "Professional Photographer", phone: "+91 99999 88888", image: "https://picsum.photos/seed/ramesh/200/200", category: "Media" },
  { name: "TasteBuds Catering", role: "Event Catering Service", phone: "+91 88888 77777", image: "https://picsum.photos/seed/catering/200/200", category: "Service", website: "https://example.com/tastebuds" },
  { name: "Ali Hassan", role: "Local Tourist Guide", phone: "+91 77777 66666", image: "https://picsum.photos/seed/ali/200/200", category: "Tourism" },
  { name: "LensMagic Videography", role: "Drone & Event Videographer", phone: "+91 66666 55555", image: "https://picsum.photos/seed/lens/200/200", category: "Media" },
];

export const BUSINESS_LISTINGS = [
  { id: "boat-sale-1", type: "sell", typeLabel: "For Sale", date: "Today", title: "Fishing Boat — 25 Feet FRP", desc: "Good condition fiberglass boat, 2022 model. Engine included. Ready to sail.", price: "₹ 3,50,000", contact: "+919876543210", contactName: "Abdul Rahman", contactDesc: "Local fisherman with 20 years experience.", images: ["https://picsum.photos/seed/boat1/400/300", "https://picsum.photos/seed/boat2/400/300"], lat: 11.1645, lng: 75.7990 },
  { id: "house-rent-1", type: "rent", typeLabel: "Rent", date: "Yesterday", title: "2BHK House Near Beach Road", desc: "Fully furnished, ground floor. Suitable for family. Near Chaliyam Junction.", price: "₹ 8,000/mo", contact: "+919876543211", contactName: "Suresh Kumar", contactDesc: "Property owner", images: ["https://picsum.photos/seed/house1/400/300"], lat: 11.1577, lng: 75.8014 },
  { id: "bike-sale-1", type: "sell", typeLabel: "For Sale", date: "2 days ago", title: "Hero Splendor — 2021", desc: "Single owner, 12,000 km run. All documents clear. Excellent condition.", price: "₹ 65,000", contact: "+919876543212", contactName: "Mohammed Ali", contactDesc: "First owner", images: ["https://picsum.photos/seed/bike1/400/300"], lat: 11.1534, lng: 75.8126 },
  { id: "plumbing-1", type: "service", typeLabel: "Service", date: "3 days ago", title: "Plumbing & Pipe Work", desc: "All types of plumbing work. Call for free estimate. Available 7 days.", price: "Call for rate", contact: "+919876543213", contactName: "Rajan Plumber", contactDesc: "Certified plumber with 15 years in Chaliyam.", images: [], lat: 11.1559, lng: 75.8112 },
  { id: "nets-wanted-1", type: "buy", typeLabel: "Wanted", date: "4 days ago", title: "Wanted: Used Fishing Nets", desc: "Looking for used nylon fishing nets in good condition. Any quantity.", price: "Best price offered", contact: "+919876543214", contactName: "Koya", contactDesc: "Wholesale fish merchant", images: [], lat: 11.1660, lng: 75.8040 },
  { id: "fish-bulk-1", type: "sell", typeLabel: "For Sale", date: "5 days ago", title: "Fresh Prawns & Fish — Bulk", desc: "Fresh daily catch available for bulk buyers. Contact morning 6–9 AM.", price: "Market Rate", contact: "+919876543215", contactName: "Hassan", contactDesc: "Boat owner", images: ["https://picsum.photos/seed/fish1/400/300"], lat: 11.1645, lng: 75.7990 },
  { id: "tuition-1", type: "service", typeLabel: "Service", date: "1 week ago", title: "Home Tuition — Maths & Science", desc: "Experienced teacher offering home tuition for Classes 8–12. CBSE/State.", price: "₹ 800/month", contact: "+919876543216", contactName: "Priya Teacher", contactDesc: "M.Sc B.Ed qualified teacher", images: [], lat: 11.1559, lng: 75.8112 },
  { id: "shop-rent-1", type: "rent", typeLabel: "Rent", date: "1 week ago", title: "Shop Space for Rent", desc: "150 sq ft shop space at Chaliyam main road. Suitable for any business.", price: "₹ 5,000/mo", contact: "+919876543217", contactName: "Manoj", contactDesc: "Building owner", images: ["https://picsum.photos/seed/shop1/400/300"], lat: 11.1534, lng: 75.8126 },
];
